### ISSUE TITLE
Add redundant RTCs capable of independent power cycling and tolerant of !SD event

### ISSUE THREAD

**Issue by heliochronix** [oresat/oresat-c3#10]
We need two additional RTCs with capacitors to maintain their power in the event of a !SD event (global watchdog shutdown), but that are also capable of being independently power cycled by the MCU.

**Comment by andrewgreenberg** [comment]
Yeah, you don't get two. But I'll give you one. With EEPROM, and SRAM. And with a Cap/Supercap backup, with ability to power cycle it. It's the Micro Crystal RV-3028 Go nuts!
