### ISSUE TITLE
Radio IRQ lines need to be on different pad numbers

### ISSUE THREAD

**Issue by heliochronix** [oresat/oresat-c3#16]
The radio IRQ lines need to be on different pad number from other GPIO ports. This is due to restrictions in the STM32 EXTI architecture as shown in the following image. Currently they are on PA8 and PD8, but one of them must be on a pin other than the respective port's pin "8".
![image](https://user-images.githubusercontent.com/1733202/93532744-7104ba80-f8f6-11ea-91ad-c6d4fd366ebc.png)

**Comment by andrewgreenberg** [comment]
LBAND_IRQ is now on PD12 and UHF_IRQ is now on PD10. Let me know if that does NOT work ASAP, else close this issue.

**Comment by heliochronix** [comment]
Works
