### ISSUE TITLE
Rename RADIO# nets to respective radio names

### ISSUE THREAD

**Issue by heliochronix** [oresat/oresat-c3#17]
Instead of nets like RADIO2_IRQ and RADIO1_CS coming off the MCU, rename according to the following mapping:

RADIO1 -> LBAND
RADIO2 -> UHF

Thus, for example, the nets would be named as UHF_IRQ or LBAND_CS to help differentiate between which radio each line is meant for.

**Comment by andrewgreenberg** [comment]
Done.
