### ISSUE TITLE
Move components on RADIO_ANALOG_1 and N$5 to other side of input filter

### ISSUE THREAD

**Issue by glennl** [oresat/oresat-c3#18]
The idea is to have the RC filter for an analog input close to the CPU. This would cause the filter components and two nets currently placed to require rework. Andrew may reasonably argue this is not worth the effort. :) Parts of this are now airwires and there are two connections, RADIO_ANALOG_1 and N$5.

**Comment by andrewgreenberg** [comment]
No room at the inn; leaving analog filters next to the log amps.
