### ISSUE TITLE
Important: Add PCB inductance between Q7 emitter and ground

### ISSUE THREAD

**Issue by glennl** [oresat/oresat-c3#47]
There is a needed inductance formed by traces on the PCB between the two emitter pins of Q7, and the surrounding ground plane. This inductance is very small, but essential as a form of regeneration to maintain stability. The inductance was provided on the dev boards, but was incorrectly changed as far back as v3. There was a fix applied to v5 boards by trimming away part of the PCB trace, and that confirmed its requirement, as shown in testing that the LNA breaks into oscillation when temperature is at or below room temp.

The trace inductor needs to correctly be applied to the board, and indicated on the schematic using an inductor symbol, and noted that it is formed by a PCB trace of some specified dimensions.

**Comment by glennl** [comment]
This may be the same as issue #44?

**Comment by andrewgreenberg** [comment]
Added emitter degenerattion like the "LEGO" board. Moving other components next door since we have more room now.
