### ISSUE TITLE
Add specialized RF test points for easy probing

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-c3#52]
Come up with a common spacing for SMT pad (0.38 mm wide so it doesn't affect the trace) and a ground pin for both the RF probe and regular scope probes.

**Comment by glennl** [comment]
At these test points point, it is expected that UT-047 semi rigid coax is to be attached. There is a pre-formed product from DigiKey ([931-1391-ND](https://www.digikey.com/en/products/detail/taoglas-limited/CAB-058/5287277?s=N4IgTCBcDaIJwGYCMBaJC6oHIBEQF0BfIA)) to implement this.

**Comment by andrewgreenberg** [comment]
This is done; See new "mask only" TPs meant to be overlayed on the RF trace. There are two FAB circles for putting GND vias, and then the GND - signal - GND spacing of 1 mm nicely allows for probing with this test probe: https://www.ebay.com/itm/185381060789
