### ISSUE TITLE
Replace UHF discrete transistor LNA with MMIC

### ISSUE THREAD

**Issue by glennl** [oresat/oresat-c3#54]
The transistor LNA has demonstrated problems when it's output is not properly matched. The proposed MMIC LNA provides very similar performance with far better stability. This subsystem is suspected to be the root cause of our UHF Rx failure in OreSat0.

Remove;
Components inside the design block called "UHF Rx LNA, 21 dB" consisting of transistor Q9

Replace with;
TQP3M9036 MMIC
https://www.mouser.com/datasheet/2/412/TQP3M9036_Data_Sheet-1500677.pdf

**Comment by cesarordaz** [comment]
Replaced the LNA, still needs a little bit of design work
