### ISSUE TITLE
Cream layer on U20 and U10 too small

### ISSUE THREAD

**Issue by davidalay** [oresat/oresat-c3#6]
the slots on the cream layer for U20 and U10 are too small, it is difficult the paste through.  I would suggest making them a tiny bit bigger (a little change goes a long way).

**Comment by andrewgreenberg** [comment]
Fixed U10 (synthesizer) - it had custom solder paste apertures that were just too small. 

U20 is a differen't beast. It's _small_. Not sure what to do, putting this off until other ICs are there.
