### ISSUE TITLE
OK to change R109 to 22k?

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-c3#64]
I'd like to change R109 from 15k to 22k. This means the TOT voltage will rise from 0.43V to 0.60V. Is that OK? We'd get to save a whole resistor value, which would be nice.

**Comment by glennl** [comment]
I strongly vote no, since this will require a higher power level to qualify the transmission as a valid power level for the watchdog. This will require testing to confirm an acceptable power range. If only to simplify parts inventory, it's not worth it.
